module.exports = [
    {
      id: "001",
      name: "Sword",
      class: "Weapon",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Sword2",
      class: "Weapon",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Sword3",
      class: "Weapon",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Helmet",
      class: "Armor",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Helmet",
      class: "Armor",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Helmet",
      class: "Armor",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Helmet",
      class: "Armor",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Helmet",
      class: "Armor",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Helmet",
      class: "Armor",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Helmet",
      class: "Armor",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Helmet",
      class: "Armor",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Helmet",
      class: "Armor",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Helmet",
      class: "Armor",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Helmet",
      class: "Armor",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Helmet",
      class: "Armor",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Helmet",
      class: "Armor",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Helmet",
      class: "Armor",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Helmet",
      class: "Armor",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },
    {
      id: "001",
      name: "Helmet",
      class: "Armor",
      img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
      price: 100,
      power: 200,
    },

    
    ]