const mongoose = require('mongoose')
const Schema = mongoose.Schema

const itemSchema = new Schema ({
  id: Number,
  name: String,
  class: String,
  img: String,
  price: Number,
  power: Number,
})

const Items = mongoose.model('Items', itemSchema)

module.exports = Items

// module.exports = [
//     {
//       id: "001",
//       name: "Sword",
//       class: "Weapon",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Sword2",
//       class: "Weapon",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Sword3",
//       class: "Weapon",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100000,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Helmet",
//       class: "Armor",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Helmet",
//       class: "Armor",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Helmet",
//       class: "Armor",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Helmet",
//       class: "Armor",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Helmet",
//       class: "Armor",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Helmet",
//       class: "Armor",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Helmet",
//       class: "Armor",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Helmet",
//       class: "Armor",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Helmet",
//       class: "Armor",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Helmet",
//       class: "Armor",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Helmet",
//       class: "Armor",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Helmet",
//       class: "Armor",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Helmet",
//       class: "Armor",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Helmet",
//       class: "Armor",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Helmet",
//       class: "Armor",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },
//     {
//       id: "001",
//       name: "Helmet",
//       class: "Armor",
//       img: "http://img.pokemondb.net/artwork/bulbasaur.jpg",
//       price: 100,
//       power: 200,
//     },

    
//     ]